### ISSUE TITLE
Fetch Api

### ISSUE THREAD

**Issue by SunriseLong** [tagr-dev/tagr#10]
Users should be able to retrieve the artifacts they've serialized to metadata providers idiomatically. 

On `tag.flush` we serialize the and tagged object as well as a `df_summary.json` file. 

The api should provide an interactive interface for user such that they never need to navigate away from their python session. 

tag.list('waterflow-tagr', 'dev/eric', 'aws') => print all flushes. list
ex: 
`['2020-07-21 19:54:17.605357', '2020-02-05 19:54:17.632321', '2020-12-20 19:54:17.312312312']`

tag.list('waterflow-tagr', 'dev/eric', 'aws').verbose() => list all flushes and the names of files under them. dict of lists
ex:
```
{'2020-07-21 19:54:17.605357':
   [X_train.csv,
   y_train.csv,
   lin_model.pkl],
   '2020-09-21 19:54:17.605357':
   [X_train.csv,
   y_train.csv,
   X_test.csv,
   lin_model.pkl,
   rf_model.pkl]
}
```

tag.list('waterflow-tagr', 'dev/eric', 'aws', 'demo', '2020-07-21 19:54:17.605357') => list all artifacts in that specific flush, list
ex:
`X_train.csv,
   y_train.csv,
   X_test.csv,
   lin_model.pkl,
   rf_model.pkl]`

tag.get(). same constructor as above but rather than getting names, returns a object with the artifacts as attributes. 

```
retireved_experiment = tag.get('waterflow-tagr', 'dev/eric', 'aws', 'demo', '2020-07-21 19:54:17.605357') 
retireved_experiment.X_train 
# Returns => X_train as a dataframe
```

```
retireved_experiment = tag.get('waterflow-tagr', 'dev/eric', 'aws', 'demo', '2020-07-21 19:54:17.605357') 
retireved_experiment.lin_model 
# Returns => the model, deserialized from pickle as a python object
```

**Comment by ericlee0112** [comment]
Question thats not directly related to this:
Lets say the user's configured the following:
```
name: "mejuri"                                                     (bucket name)
experiment: "knn-experiment"                           (experiment name)
version: "0.1"                                                        (optional for name spacing)
profile: "mejuri-aws-ds"                                      (name of profile to use in `profiles.yml`)
```

When a user flushes, would tagr add the metadata in this path like this:
```
mejuri
     /knn-experiment
          /2020-02-25 19:54:17.632321
               -X_train.csv,
               -y_train.csv,
               -lin_model.pkl
```

And then that way, we can programmatically fetch by looking up that particular directory
```
tag.list('mejuri', 'knn-experiment', 'aws')
```

lmk if theres anything wrong

**Comment by SunriseLong** [comment]
yes

**Comment by SunriseLong** [comment]
if they want to hone on specific run they can do 
tag.list('mejuri', 'knn-experiment', '2020-02-25 19:54:17.63232', 'aws')

**Comment by ericlee0112** [comment]
Seems that for this, we're going to need possibly 2-3 new methods for Artifacts.py. One for listing files/folders and another for fetching experiment artifacts. This feature might take a few PRs

**Comment by ericlee0112** [comment]
.list() and .fetch() have now been implemented and merged to master. Closing this issue
